name: Package World of Warcraft addon
run-name: Release ${{github.ref_name}}

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  package:
    name: Create release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Get name of addon
      id: init
      run: |
        addon_name=$(ls *.toc)
        addon_name=$(basename $addon_name .toc)
        echo "addon_name=$addon_name" >> $GITHUB_OUTPUT

    - name: Make folder for zips
      run: |
        mkdir -p .release
        rsync -r --exclude '.*' . .release

    - name: Replace TOC version
      run: |
        sed -i 's/Version: GIT\+/Version: ${{github.ref_name}}/g' .release/${{steps.init.outputs.addon_name}}.toc

    - name: Create zip
      run: |
        cd .release
        zip -9 -r ${{steps.init.outputs.addon_name}}.zip .
        cd ..

    - name: Update release
      uses: ncipollo/release-action@v1.14.0
      with:
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        artifacts: .release/*.zip
